wordCountApp/urls.py
from django.contrib import admin
from django.urls import include,  path
from wordcount import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('wordcount.urls')),
]

wordcount/urls.py
from django.urls import path
from wordcount import views

app_name = 'wordcount'

urlpatterns = [
    path('', views.word_count, name='word_count'),
]

wordcount/models.py
from django.db import models

# Create your models here.

wordcount/views.py
from django.shortcuts import render

# Create your views here.
def word_count(request):
    if request.method == 'POST':
        text = request.POST['text']
        word_count = len(text.split())
        return render(request, 'wordcount/result.html', {'count': word_count})
    return render(request, 'wordcount/wordcount.html')

wordcount/templates/wordcount/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Word Count Result </title>
</head>
<body>
    <h1> Word Count Result </h1>
    <p> The number of word in the text is: {{ count }} </p>
    <a hred="{% url 'wordcount:word_count' %}"> Go Back </a>
</body>
</html>

wordcount/templates/wordcount/wordcount.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Word Count </title>
</head>
<body>
    <h1> Word Count Tool </h1>
    <form method="post" action="{% url 'wordcount:word_count' %}">
        {% csrf_token %}
        <label for="text"> Enter the text: </label> <br>
        <textarea id="text" name="text"> </textarea> <br>
        <button type="submit"> Count Words </button>
    </form>
</body>
</html>